# Form implementation generated from reading ui file './pyqt6/designer/componenta.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ComponentA(object):
    def setupUi(self, ComponentA):
        ComponentA.setObjectName("ComponentA")
        ComponentA.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ComponentA)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=ComponentA)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.spinBox = QtWidgets.QSpinBox(parent=ComponentA)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.textEdit = QtWidgets.QTextEdit(parent=ComponentA)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=ComponentA)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout.addWidget(self.doubleSpinBox)
        self.horizontalSlider = QtWidgets.QSlider(parent=ComponentA)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)

        self.retranslateUi(ComponentA)
        QtCore.QMetaObject.connectSlotsByName(ComponentA)

    def retranslateUi(self, ComponentA):
        _translate = QtCore.QCoreApplication.translate
        ComponentA.setWindowTitle(_translate("ComponentA", "Form"))
