# Form implementation generated from reading ui file './pyqt6/designer/componentb.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ComponentB(object):
    def setupUi(self, ComponentB):
        ComponentB.setObjectName("ComponentB")
        ComponentB.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ComponentB)
        self.verticalLayout.setObjectName("verticalLayout")
        self.spinBox = QtWidgets.QSpinBox(parent=ComponentB)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.timeEdit = QtWidgets.QTimeEdit(parent=ComponentB)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout.addWidget(self.timeEdit)
        self.comboBox = QtWidgets.QComboBox(parent=ComponentB)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.dial = QtWidgets.QDial(parent=ComponentB)
        self.dial.setObjectName("dial")
        self.verticalLayout.addWidget(self.dial)

        self.retranslateUi(ComponentB)
        QtCore.QMetaObject.connectSlotsByName(ComponentB)

    def retranslateUi(self, ComponentB):
        _translate = QtCore.QCoreApplication.translate
        ComponentB.setWindowTitle(_translate("ComponentB", "Form"))
